# Generated by Django 3.2.13 on 2022-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20220422_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diak',
            name='nev',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='diak',
            name='pontszam',
            field=models.IntegerField(),
        ),
    ]
