# Generated by Django 3.2.13 on 2022-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20220422_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diak',
            name='pontszam',
            field=models.IntegerField(),
        ),
    ]
