# Generated by Django 3.2.13 on 2022-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_diak_pontszam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diak',
            name='pontszam',
            field=models.IntegerField(),
        ),
    ]
