# Generated by Django 3.2.13 on 2022-05-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20220422_1124'),
        ('APP', '0005_alter_diak_pontszam'),
    ]

    operations = [
    ]
