# Generated by Django 3.2.13 on 2022-05-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_merge_20220513_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diak',
            name='Aosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Bosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Cosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Dosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Eosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Fosztaly',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='om',
        ),
    ]
